server {
    listen ${PORT};
    server_name localhost;

    root /app/data;
    index index.html;

    gzip on;
    gzip_types text/html text/css application/javascript application/xml;

    location / {
        try_files $uri $uri/ @extensionless;
    }

    location @extensionless {
        rewrite ^(.*)$ $1.html last;
    }
}
